language: android
jdk: oraclejdk8
cache: false
sudo: true
android:
  components:
  - build-tools-26.0.2
  - android-26
  - android-25
  - android-24
  - extra-android-m2repository
  - extra-android-support
script:
- cp -f ./build_var_config ./build_var_controls/bk
- "./gradlew clean"
- "./gradlew assembleRelease"
- cp app/build/outputs/apk/release/app-release.apk app/app-release-default.apk
- cp -f ./build_var_controls/build_var_config_stable_play ./build_var_config
- "./gradlew clean"
- "./gradlew assembleRelease"
- cp app/build/outputs/apk/release/app-release.apk app/app-release-stable-play.apk
- cp -f ./build_var_controls/build_var_config_aio ./build_var_config
- "./gradlew clean"
- "./gradlew assembleRelease"
- cp app/build/outputs/apk/release/app-release.apk app/app-release-aio.apk
- cp -f ./build_var_controls/bk ./build_var_config
- git checkout build_var_config
before_script:
- mkdir -p "$ANDROID_HOME/licenses"
- cp ./android-sdk-license "$ANDROID_HOME/licenses/"
- cp ./hiddenapi/26/android.jar "$ANDROID_HOME/platforms/android-26/"
- cp ./hiddenapi/25/android.jar "$ANDROID_HOME/platforms/android-25/"
- openssl enc -des-ede3-cbc -in ./google-services-enc.json -out ./app/google-services.json -d -k $KEYSTORE_PASS
after_script:
- rm -rf ./app/google-services.json
notifications:
  email:
    recipients:
    - tornaco@163.com
    on_success: always
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_9386c2da478c_key -iv $encrypted_9386c2da478c_iv
  -in keys_android.jks.enc -out keys/keys_android.jks -d
deploy:
  provider: releases
  api_key:
    secure: QGGIdCX9U+piuLrgHk7KhC3gIKJg7JeqocLWKw5g0lfdbcNjEUWO/mDSs8ucqk27WIoD/Nj0uzRGFq6P68WIpehpwEjoCild4bfTFhQomGG/kJ1GnvlPFG0K13qB0Ll3PXrRt661OAQcnpbiGzwoaiJOe+BozOCcmuJQxvCbATj8VQ88uZeCE4w+Ap/4FraCMb8qifeme2QjFZoXzh6zHelT13IB23+HQRCGczbalgmhUXo+rk8aCd+WE8MzDny9mOMizcMXG78kdhYzSJfW9B2WwFg6iKSkxPdkRvQedLr+sVA4katRhnUr5uJ1hOBnjB0KxPjUu44DEWaVBjqCzXAJh/z5CLLwmhi4qoKbc60LReiwCwgRuUNqeIYyIWO4fCwEY1SahL03jNjVQm9DI9mPGsUzwKY088hFqe5im79PCdWQETvnxGtSFWhqmztd1WwlAJZBc8zXbK99vf3DTa0yI3OU9XaIN8cgTIckWtavC3yY0Yuj2HIvGWaU4emE0LoNVSsQCUg/78rmy9GeKGtnHQJY5/LJC1xogP3IxQyiVDDU+HgE/8Be1l8ZtNw0/8DiFRCMckYrotpvtoG6ATzmVf+VLqGMs3EYG6a52LL5tPFWUl8HF2Ng2St/M6nk9C8hStyKpdhyJsLWX5sA25UzOg1itXIvyc90gAUnGtY=
  file:
  - app/app-release-default.apk
  - app/app-release-stable-play.apk
  - app/app-release-aio.apk
  skip_cleanup: true
  on:
    repo: Tornaco/X-APM
    tags: true
    all_branches: true
