package github.tornaco.xposedmoduletest.bean;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

import java.util.Objects;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "RECENT_TILE".
 */
@Entity
public class RecentTile {

    @Id
    private Integer id;
    private String tileKey;
    private Long lastUsed;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 1402732903)
    public RecentTile() {
    }

    public RecentTile(Integer id) {
        this.id = id;
    }

    @Generated(hash = 569335284)
    public RecentTile(Integer id, String tileKey, Long lastUsed) {
        this.id = id;
        this.tileKey = tileKey;
        this.lastUsed = lastUsed;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTileKey() {
        return tileKey;
    }

    public void setTileKey(String tileKey) {
        this.tileKey = tileKey;
    }

    public Long getLastUsed() {
        return lastUsed;
    }

    public void setLastUsed(Long lastUsed) {
        this.lastUsed = lastUsed;
    }

    // KEEP METHODS - put your custom methods here
    public static RecentTile from(String key) {
        RecentTile t = new RecentTile();
        t.tileKey = key;
        t.lastUsed = System.currentTimeMillis();
        return t;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        RecentTile that = (RecentTile) o;
        return Objects.equals(tileKey, that.tileKey);
    }

    @Override
    public int hashCode() {

        return Objects.hash(tileKey);
    }

    // KEEP METHODS END

}
