package github.tornaco.xposedmoduletest.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BOOT_COMPLETE_PACKAGE".
 */
public class BootCompletePackage {

    private Integer id;
    private String pkgName;
    private String appName;
    private Boolean allow;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BootCompletePackage() {
    }

    public BootCompletePackage(Integer id) {
        this.id = id;
    }

    public BootCompletePackage(Integer id, String pkgName, String appName, Boolean allow) {
        this.id = id;
        this.pkgName = pkgName;
        this.appName = appName;
        this.allow = allow;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPkgName() {
        return pkgName;
    }

    public void setPkgName(String pkgName) {
        this.pkgName = pkgName;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public Boolean getAllow() {
        return allow;
    }

    public void setAllow(Boolean allow) {
        this.allow = allow;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
