package github.tornaco.xposedmoduletest.bean;

import com.google.gson.Gson;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Transient;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "COMPONENT_REPLACEMENT".
 */
@Entity
public class ComponentReplacement {

    @Id
    private Integer id;
    private String appPackageName;
    private String compFromPackageName;
    private String compFromClassName;
    private String compToPackageName;
    private String compToClassName;

    @Transient
    private String appName;

    @Generated(hash = 674511864)
    public ComponentReplacement() {
    }

    public ComponentReplacement(Integer id) {
        this.id = id;
    }

    @Generated(hash = 1839575346)
    public ComponentReplacement(Integer id, String appPackageName, String compFromPackageName,
                                String compFromClassName, String compToPackageName, String compToClassName) {
        this.id = id;
        this.appPackageName = appPackageName;
        this.compFromPackageName = compFromPackageName;
        this.compFromClassName = compFromClassName;
        this.compToPackageName = compToPackageName;
        this.compToClassName = compToClassName;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAppPackageName() {
        return appPackageName;
    }

    public void setAppPackageName(String appPackageName) {
        this.appPackageName = appPackageName;
    }

    public String getCompFromPackageName() {
        return compFromPackageName;
    }

    public void setCompFromPackageName(String compFromPackageName) {
        this.compFromPackageName = compFromPackageName;
    }

    public String getCompFromClassName() {
        return compFromClassName;
    }

    public void setCompFromClassName(String compFromClassName) {
        this.compFromClassName = compFromClassName;
    }

    public String getCompToPackageName() {
        return compToPackageName;
    }

    public void setCompToPackageName(String compToPackageName) {
        this.compToPackageName = compToPackageName;
    }

    public String getCompToClassName() {
        return compToClassName;
    }

    public void setCompToClassName(String compToClassName) {
        this.compToClassName = compToClassName;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "ComponentReplacement{" +
                "id=" + id +
                ", appPackageName='" + appPackageName + '\'' +
                ", compFromPackageName='" + compFromPackageName + '\'' +
                ", compFromClassName='" + compFromClassName + '\'' +
                ", compToPackageName='" + compToPackageName + '\'' +
                ", compToClassName='" + compToClassName + '\'' +
                '}';
    }

    public String fromFlattenToString() {
        return compFromPackageName + "/" + compFromClassName;
    }

    public String toFlattenToString() {
        return compToPackageName + "/" + compToClassName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getAppName() {
        return appName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        ComponentReplacement that = (ComponentReplacement) o;

        if (!compFromPackageName.equals(that.compFromPackageName)) return false;
        if (!compFromClassName.equals(that.compFromClassName)) return false;
        if (compToPackageName != null ? !compToPackageName.equals(that.compToPackageName) : that.compToPackageName != null)
            return false;
        return compToClassName != null ? compToClassName.equals(that.compToClassName) : that.compToClassName == null;
    }

    @Override
    public int hashCode() {
        int result = compFromPackageName.hashCode();
        result = 31 * result + compFromClassName.hashCode();
        result = 31 * result + (compToPackageName != null ? compToPackageName.hashCode() : 0);
        result = 31 * result + (compToClassName != null ? compToClassName.hashCode() : 0);
        return result;
    }

    public String toJson() {
        return new Gson().toJson(this);
    }

    public static ComponentReplacement fromJson(String json) {
        if (json == null) return null;
        try {
            return new Gson().fromJson(json, ComponentReplacement.class);
        } catch (Throwable e) {
            return null;
        }
    }

    // KEEP METHODS END

}
