package github.tornaco.xposedmoduletest.bean;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "CONGFIGURATION_SETTING".
 */
@Entity
public class CongfigurationSetting {

    @Id
    private Integer id;
    private String packageName;
    private Integer densityDpi;
    private Float fontScale;
    private Integer orientation;
    private Integer screenHeightDp;
    private Integer screenWidthDp;
    private Boolean excludeFromRecent;
    private Boolean uiMode;
    private Integer intArg0;
    private String stringArg0;
    private Float floatArg0;
    private Long longArg0;
    private Boolean boolArg0;
    private Integer intArg1;
    private String stringArg1;
    private Float floatArg1;
    private Long longArg1;
    private Boolean boolArg1;
    private Integer intArg2;
    private String stringArg2;
    private Float floatArg2;
    private Long longArg2;
    private Boolean boolArg2;
    private Integer intArg3;
    private String stringArg3;
    private Float floatArg3;
    private Long longArg3;
    private Boolean boolArg3;
    private Integer intArg4;
    private String stringArg4;
    private Float floatArg4;
    private Long longArg4;
    private Boolean boolArg4;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 2077404040)
    public CongfigurationSetting() {
    }

    public CongfigurationSetting(Integer id) {
        this.id = id;
    }

    @Generated(hash = 714572133)
    public CongfigurationSetting(Integer id, String packageName, Integer densityDpi, Float fontScale, Integer orientation, Integer screenHeightDp, Integer screenWidthDp, Boolean excludeFromRecent, Boolean uiMode, Integer intArg0, String stringArg0, Float floatArg0, Long longArg0, Boolean boolArg0, Integer intArg1, String stringArg1, Float floatArg1, Long longArg1, Boolean boolArg1, Integer intArg2, String stringArg2, Float floatArg2, Long longArg2, Boolean boolArg2, Integer intArg3, String stringArg3, Float floatArg3, Long longArg3, Boolean boolArg3, Integer intArg4, String stringArg4, Float floatArg4, Long longArg4, Boolean boolArg4) {
        this.id = id;
        this.packageName = packageName;
        this.densityDpi = densityDpi;
        this.fontScale = fontScale;
        this.orientation = orientation;
        this.screenHeightDp = screenHeightDp;
        this.screenWidthDp = screenWidthDp;
        this.excludeFromRecent = excludeFromRecent;
        this.uiMode = uiMode;
        this.intArg0 = intArg0;
        this.stringArg0 = stringArg0;
        this.floatArg0 = floatArg0;
        this.longArg0 = longArg0;
        this.boolArg0 = boolArg0;
        this.intArg1 = intArg1;
        this.stringArg1 = stringArg1;
        this.floatArg1 = floatArg1;
        this.longArg1 = longArg1;
        this.boolArg1 = boolArg1;
        this.intArg2 = intArg2;
        this.stringArg2 = stringArg2;
        this.floatArg2 = floatArg2;
        this.longArg2 = longArg2;
        this.boolArg2 = boolArg2;
        this.intArg3 = intArg3;
        this.stringArg3 = stringArg3;
        this.floatArg3 = floatArg3;
        this.longArg3 = longArg3;
        this.boolArg3 = boolArg3;
        this.intArg4 = intArg4;
        this.stringArg4 = stringArg4;
        this.floatArg4 = floatArg4;
        this.longArg4 = longArg4;
        this.boolArg4 = boolArg4;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public Integer getDensityDpi() {
        return densityDpi;
    }

    public void setDensityDpi(Integer densityDpi) {
        this.densityDpi = densityDpi;
    }

    public Float getFontScale() {
        return fontScale;
    }

    public void setFontScale(Float fontScale) {
        this.fontScale = fontScale;
    }

    public Integer getOrientation() {
        return orientation;
    }

    public void setOrientation(Integer orientation) {
        this.orientation = orientation;
    }

    public Integer getScreenHeightDp() {
        return screenHeightDp;
    }

    public void setScreenHeightDp(Integer screenHeightDp) {
        this.screenHeightDp = screenHeightDp;
    }

    public Integer getScreenWidthDp() {
        return screenWidthDp;
    }

    public void setScreenWidthDp(Integer screenWidthDp) {
        this.screenWidthDp = screenWidthDp;
    }

    public Boolean getExcludeFromRecent() {
        return excludeFromRecent;
    }

    public void setExcludeFromRecent(Boolean excludeFromRecent) {
        this.excludeFromRecent = excludeFromRecent;
    }

    public Boolean getUiMode() {
        return uiMode;
    }

    public void setUiMode(Boolean uiMode) {
        this.uiMode = uiMode;
    }

    public Integer getIntArg0() {
        return intArg0;
    }

    public void setIntArg0(Integer intArg0) {
        this.intArg0 = intArg0;
    }

    public String getStringArg0() {
        return stringArg0;
    }

    public void setStringArg0(String stringArg0) {
        this.stringArg0 = stringArg0;
    }

    public Float getFloatArg0() {
        return floatArg0;
    }

    public void setFloatArg0(Float floatArg0) {
        this.floatArg0 = floatArg0;
    }

    public Long getLongArg0() {
        return longArg0;
    }

    public void setLongArg0(Long longArg0) {
        this.longArg0 = longArg0;
    }

    public Boolean getBoolArg0() {
        return boolArg0;
    }

    public void setBoolArg0(Boolean boolArg0) {
        this.boolArg0 = boolArg0;
    }

    public Integer getIntArg1() {
        return intArg1;
    }

    public void setIntArg1(Integer intArg1) {
        this.intArg1 = intArg1;
    }

    public String getStringArg1() {
        return stringArg1;
    }

    public void setStringArg1(String stringArg1) {
        this.stringArg1 = stringArg1;
    }

    public Float getFloatArg1() {
        return floatArg1;
    }

    public void setFloatArg1(Float floatArg1) {
        this.floatArg1 = floatArg1;
    }

    public Long getLongArg1() {
        return longArg1;
    }

    public void setLongArg1(Long longArg1) {
        this.longArg1 = longArg1;
    }

    public Boolean getBoolArg1() {
        return boolArg1;
    }

    public void setBoolArg1(Boolean boolArg1) {
        this.boolArg1 = boolArg1;
    }

    public Integer getIntArg2() {
        return intArg2;
    }

    public void setIntArg2(Integer intArg2) {
        this.intArg2 = intArg2;
    }

    public String getStringArg2() {
        return stringArg2;
    }

    public void setStringArg2(String stringArg2) {
        this.stringArg2 = stringArg2;
    }

    public Float getFloatArg2() {
        return floatArg2;
    }

    public void setFloatArg2(Float floatArg2) {
        this.floatArg2 = floatArg2;
    }

    public Long getLongArg2() {
        return longArg2;
    }

    public void setLongArg2(Long longArg2) {
        this.longArg2 = longArg2;
    }

    public Boolean getBoolArg2() {
        return boolArg2;
    }

    public void setBoolArg2(Boolean boolArg2) {
        this.boolArg2 = boolArg2;
    }

    public Integer getIntArg3() {
        return intArg3;
    }

    public void setIntArg3(Integer intArg3) {
        this.intArg3 = intArg3;
    }

    public String getStringArg3() {
        return stringArg3;
    }

    public void setStringArg3(String stringArg3) {
        this.stringArg3 = stringArg3;
    }

    public Float getFloatArg3() {
        return floatArg3;
    }

    public void setFloatArg3(Float floatArg3) {
        this.floatArg3 = floatArg3;
    }

    public Long getLongArg3() {
        return longArg3;
    }

    public void setLongArg3(Long longArg3) {
        this.longArg3 = longArg3;
    }

    public Boolean getBoolArg3() {
        return boolArg3;
    }

    public void setBoolArg3(Boolean boolArg3) {
        this.boolArg3 = boolArg3;
    }

    public Integer getIntArg4() {
        return intArg4;
    }

    public void setIntArg4(Integer intArg4) {
        this.intArg4 = intArg4;
    }

    public String getStringArg4() {
        return stringArg4;
    }

    public void setStringArg4(String stringArg4) {
        this.stringArg4 = stringArg4;
    }

    public Float getFloatArg4() {
        return floatArg4;
    }

    public void setFloatArg4(Float floatArg4) {
        this.floatArg4 = floatArg4;
    }

    public Long getLongArg4() {
        return longArg4;
    }

    public void setLongArg4(Long longArg4) {
        this.longArg4 = longArg4;
    }

    public Boolean getBoolArg4() {
        return boolArg4;
    }

    public void setBoolArg4(Boolean boolArg4) {
        this.boolArg4 = boolArg4;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "CongfigurationSetting{" +
                "id=" + id +
                ", packageName='" + packageName + '\'' +
                ", densityDpi=" + densityDpi +
                ", fontScale=" + fontScale +
                ", orientation=" + orientation +
                ", screenHeightDp=" + screenHeightDp +
                ", screenWidthDp=" + screenWidthDp +
                ", excludeFromRecent=" + excludeFromRecent +
                ", uiMode=" + uiMode +
                '}';
    }

    // KEEP METHODS END

}
