package github.tornaco.xposedmoduletest.bean;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import github.tornaco.xposedmoduletest.bean.PackageInfo;
import github.tornaco.xposedmoduletest.bean.AccessInfo;

import github.tornaco.xposedmoduletest.bean.PackageInfoDao;
import github.tornaco.xposedmoduletest.bean.AccessInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig packageInfoDaoConfig;
    private final DaoConfig accessInfoDaoConfig;

    private final PackageInfoDao packageInfoDao;
    private final AccessInfoDao accessInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        packageInfoDaoConfig = daoConfigMap.get(PackageInfoDao.class).clone();
        packageInfoDaoConfig.initIdentityScope(type);

        accessInfoDaoConfig = daoConfigMap.get(AccessInfoDao.class).clone();
        accessInfoDaoConfig.initIdentityScope(type);

        packageInfoDao = new PackageInfoDao(packageInfoDaoConfig, this);
        accessInfoDao = new AccessInfoDao(accessInfoDaoConfig, this);

        registerDao(PackageInfo.class, packageInfoDao);
        registerDao(AccessInfo.class, accessInfoDao);
    }
    
    public void clear() {
        packageInfoDaoConfig.getIdentityScope().clear();
        accessInfoDaoConfig.getIdentityScope().clear();
    }

    public PackageInfoDao getPackageInfoDao() {
        return packageInfoDao;
    }

    public AccessInfoDao getAccessInfoDao() {
        return accessInfoDao;
    }

}
