package github.tornaco.xposedmoduletest.bean;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import github.tornaco.xposedmoduletest.bean.PackageInfo;
import github.tornaco.xposedmoduletest.bean.AccessInfo;
import github.tornaco.xposedmoduletest.bean.BootCompletePackage;
import github.tornaco.xposedmoduletest.bean.AutoStartPackage;
import github.tornaco.xposedmoduletest.bean.LockKillPackage;
import github.tornaco.xposedmoduletest.bean.BlockRecord;

import github.tornaco.xposedmoduletest.bean.PackageInfoDao;
import github.tornaco.xposedmoduletest.bean.AccessInfoDao;
import github.tornaco.xposedmoduletest.bean.BootCompletePackageDao;
import github.tornaco.xposedmoduletest.bean.AutoStartPackageDao;
import github.tornaco.xposedmoduletest.bean.LockKillPackageDao;
import github.tornaco.xposedmoduletest.bean.BlockRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig packageInfoDaoConfig;
    private final DaoConfig accessInfoDaoConfig;
    private final DaoConfig bootCompletePackageDaoConfig;
    private final DaoConfig autoStartPackageDaoConfig;
    private final DaoConfig lockKillPackageDaoConfig;
    private final DaoConfig blockRecordDaoConfig;

    private final PackageInfoDao packageInfoDao;
    private final AccessInfoDao accessInfoDao;
    private final BootCompletePackageDao bootCompletePackageDao;
    private final AutoStartPackageDao autoStartPackageDao;
    private final LockKillPackageDao lockKillPackageDao;
    private final BlockRecordDao blockRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        packageInfoDaoConfig = daoConfigMap.get(PackageInfoDao.class).clone();
        packageInfoDaoConfig.initIdentityScope(type);

        accessInfoDaoConfig = daoConfigMap.get(AccessInfoDao.class).clone();
        accessInfoDaoConfig.initIdentityScope(type);

        bootCompletePackageDaoConfig = daoConfigMap.get(BootCompletePackageDao.class).clone();
        bootCompletePackageDaoConfig.initIdentityScope(type);

        autoStartPackageDaoConfig = daoConfigMap.get(AutoStartPackageDao.class).clone();
        autoStartPackageDaoConfig.initIdentityScope(type);

        lockKillPackageDaoConfig = daoConfigMap.get(LockKillPackageDao.class).clone();
        lockKillPackageDaoConfig.initIdentityScope(type);

        blockRecordDaoConfig = daoConfigMap.get(BlockRecordDao.class).clone();
        blockRecordDaoConfig.initIdentityScope(type);

        packageInfoDao = new PackageInfoDao(packageInfoDaoConfig, this);
        accessInfoDao = new AccessInfoDao(accessInfoDaoConfig, this);
        bootCompletePackageDao = new BootCompletePackageDao(bootCompletePackageDaoConfig, this);
        autoStartPackageDao = new AutoStartPackageDao(autoStartPackageDaoConfig, this);
        lockKillPackageDao = new LockKillPackageDao(lockKillPackageDaoConfig, this);
        blockRecordDao = new BlockRecordDao(blockRecordDaoConfig, this);

        registerDao(PackageInfo.class, packageInfoDao);
        registerDao(AccessInfo.class, accessInfoDao);
        registerDao(BootCompletePackage.class, bootCompletePackageDao);
        registerDao(AutoStartPackage.class, autoStartPackageDao);
        registerDao(LockKillPackage.class, lockKillPackageDao);
        registerDao(BlockRecord.class, blockRecordDao);
    }
    
    public void clear() {
        packageInfoDaoConfig.getIdentityScope().clear();
        accessInfoDaoConfig.getIdentityScope().clear();
        bootCompletePackageDaoConfig.getIdentityScope().clear();
        autoStartPackageDaoConfig.getIdentityScope().clear();
        lockKillPackageDaoConfig.getIdentityScope().clear();
        blockRecordDaoConfig.getIdentityScope().clear();
    }

    public PackageInfoDao getPackageInfoDao() {
        return packageInfoDao;
    }

    public AccessInfoDao getAccessInfoDao() {
        return accessInfoDao;
    }

    public BootCompletePackageDao getBootCompletePackageDao() {
        return bootCompletePackageDao;
    }

    public AutoStartPackageDao getAutoStartPackageDao() {
        return autoStartPackageDao;
    }

    public LockKillPackageDao getLockKillPackageDao() {
        return lockKillPackageDao;
    }

    public BlockRecordDao getBlockRecordDao() {
        return blockRecordDao;
    }

}
