package github.tornaco.xposedmoduletest.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PACKAGE_INFO".
 */
public class PackageInfo {

    private Integer id;
    private String pkgName;
    private String appName;
    private Long addAt;
    private Boolean guard;
    private Byte flags;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PackageInfo() {
    }

    public PackageInfo(Integer id) {
        this.id = id;
    }

    public PackageInfo(Integer id, String pkgName, String appName, Long addAt, Boolean guard, Byte flags) {
        this.id = id;
        this.pkgName = pkgName;
        this.appName = appName;
        this.addAt = addAt;
        this.guard = guard;
        this.flags = flags;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPkgName() {
        return pkgName;
    }

    public void setPkgName(String pkgName) {
        this.pkgName = pkgName;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public Long getAddAt() {
        return addAt;
    }

    public void setAddAt(Long addAt) {
        this.addAt = addAt;
    }

    public Boolean getGuard() {
        return guard;
    }

    public void setGuard(Boolean guard) {
        this.guard = guard;
    }

    public Byte getFlags() {
        return flags;
    }

    public void setFlags(Byte flags) {
        this.flags = flags;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        PackageInfo that = (PackageInfo) o;

        return pkgName.equals(that.pkgName);

    }

    @Override
    public int hashCode() {
        return pkgName.hashCode();
    }
    // KEEP METHODS END

}
