package github.tornaco.xposedmoduletest.bean;


import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "RFKILL_PACKAGE".
 */
@Entity
public class RFKillPackage {

    @Id
    private Integer id;
    private String pkgName;
    private String appName;
    private Boolean kill;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 2091509942)
    public RFKillPackage() {
    }

    public RFKillPackage(Integer id) {
        this.id = id;
    }

    @Generated(hash = 1088547898)
    public RFKillPackage(Integer id, String pkgName, String appName, Boolean kill) {
        this.id = id;
        this.pkgName = pkgName;
        this.appName = appName;
        this.kill = kill;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPkgName() {
        return pkgName;
    }

    public void setPkgName(String pkgName) {
        this.pkgName = pkgName;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public Boolean getKill() {
        return kill;
    }

    public void setKill(Boolean kill) {
        this.kill = kill;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
